---
- name: render files locally
  include: "render_locally.yml"
  static: no
  when: global.save_local is defined and global.save_local == "enable"
  tags:
    - ifaces_setup
    - local

- name: render files remotely
  include: render_remotely.yml
  tags:
    - ifaces_setup
